/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercicio_7;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrador
 */
public class Fundacao_Times extends javax.swing.JFrame {

    /**
     * Creates new form Fundacao_Times
     */
    public Fundacao_Times() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBGGrupoOpcoes = new javax.swing.ButtonGroup();
        jRAtleticoMG = new javax.swing.JRadioButton();
        jRAtleticoPR = new javax.swing.JRadioButton();
        jRPalmeiras = new javax.swing.JRadioButton();
        jRCorinthians = new javax.swing.JRadioButton();
        jRSantos = new javax.swing.JRadioButton();
        jRSaoPaulo = new javax.swing.JRadioButton();
        jRBotaFogo = new javax.swing.JRadioButton();
        jRFluminense = new javax.swing.JRadioButton();
        jRFlamengo = new javax.swing.JRadioButton();
        jRVasco = new javax.swing.JRadioButton();
        jRCoritiba = new javax.swing.JRadioButton();
        jRInternacional = new javax.swing.JRadioButton();
        jRGremio = new javax.swing.JRadioButton();
        jRCruzeiro = new javax.swing.JRadioButton();
        jRSport = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBGGrupoOpcoes.add(jRAtleticoMG);
        jRAtleticoMG.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jRAtleticoMG.setText("Atlético - MG");
        jRAtleticoMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRAtleticoMGActionPerformed(evt);
            }
        });

        jBGGrupoOpcoes.add(jRAtleticoPR);
        jRAtleticoPR.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jRAtleticoPR.setText("Atlético - PR");
        jRAtleticoPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRAtleticoPRActionPerformed(evt);
            }
        });

        jBGGrupoOpcoes.add(jRPalmeiras);
        jRPalmeiras.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jRPalmeiras.setText("Palmeiras");

        jBGGrupoOpcoes.add(jRCorinthians);
        jRCorinthians.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jRCorinthians.setText("Corinthians");
        jRCorinthians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCorinthiansActionPerformed(evt);
            }
        });

        jBGGrupoOpcoes.add(jRSantos);
        jRSantos.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jRSantos.setText("Santos");

        jBGGrupoOpcoes.add(jRSaoPaulo);
        jRSaoPaulo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jRSaoPaulo.setText("São Paulo");

        jBGGrupoOpcoes.add(jRBotaFogo);
        jRBotaFogo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jRBotaFogo.setText("BotaFogo");

        jBGGrupoOpcoes.add(jRFluminense);
        jRFluminense.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jRFluminense.setText("Fluminense");

        jBGGrupoOpcoes.add(jRFlamengo);
        jRFlamengo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jRFlamengo.setText("Flamengo");

        jBGGrupoOpcoes.add(jRVasco);
        jRVasco.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jRVasco.setText("Vasco");

        jBGGrupoOpcoes.add(jRCoritiba);
        jRCoritiba.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jRCoritiba.setText("Coritiba");
        jRCoritiba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCoritibaActionPerformed(evt);
            }
        });

        jBGGrupoOpcoes.add(jRInternacional);
        jRInternacional.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jRInternacional.setText("Internacional");
        jRInternacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRInternacionalActionPerformed(evt);
            }
        });

        jBGGrupoOpcoes.add(jRGremio);
        jRGremio.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jRGremio.setText("Grêmio");
        jRGremio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRGremioActionPerformed(evt);
            }
        });

        jBGGrupoOpcoes.add(jRCruzeiro);
        jRCruzeiro.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jRCruzeiro.setText("Cruzeiro");

        jBGGrupoOpcoes.add(jRSport);
        jRSport.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jRSport.setText("Sport");

        jButton1.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jButton1.setText("Veja a data de fundação");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Hulkbusters", 0, 18)); // NOI18N
        jLabel1.setText("Escolha seu Time :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRAtleticoMG)
                            .addComponent(jRAtleticoPR)
                            .addComponent(jRPalmeiras)
                            .addComponent(jRCorinthians)
                            .addComponent(jRSantos))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRFlamengo)
                            .addComponent(jRVasco)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRBotaFogo)
                                    .addComponent(jRSaoPaulo))
                                .addGap(53, 53, 53)
                                .addComponent(jRCoritiba))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRFluminense)
                                .addGap(45, 45, 45)
                                .addComponent(jRGremio))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRSport)
                                    .addComponent(jRCruzeiro)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton2)
                                        .addComponent(jRInternacional)))))))
                .addGap(27, 47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRAtleticoMG)
                    .addComponent(jRSaoPaulo)
                    .addComponent(jRCoritiba))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRAtleticoPR)
                    .addComponent(jRBotaFogo)
                    .addComponent(jRInternacional))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRPalmeiras)
                    .addComponent(jRFluminense)
                    .addComponent(jRGremio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRCorinthians)
                    .addComponent(jRFlamengo)
                    .addComponent(jRCruzeiro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRSantos)
                    .addComponent(jRVasco)
                    .addComponent(jRSport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRAtleticoMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRAtleticoMGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRAtleticoMGActionPerformed

    private void jRAtleticoPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRAtleticoPRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRAtleticoPRActionPerformed

    private void jRInternacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRInternacionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRInternacionalActionPerformed

    private void jRCoritibaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCoritibaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRCoritibaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRGremioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRGremioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRGremioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jRPalmeiras.isSelected()){
        JOptionPane.showMessageDialog(null, "26 de agosto de 1914");
        }
        else if (jRCorinthians.isSelected()){
        JOptionPane.showMessageDialog(null, "01 de setembro de 1910");
        }
        else if (jRSantos.isSelected()){
        JOptionPane.showMessageDialog(null, "14 de abril de 1912");
        }
        else if (jRSaoPaulo.isSelected()){
        JOptionPane.showMessageDialog(null, "27 de janeiro de 1930");
        }
        else if (jRBotaFogo.isSelected()){
        JOptionPane.showMessageDialog(null, "01 de julho de 1894");
        }
        else if (jRFluminense.isSelected()){
        JOptionPane.showMessageDialog(null, "21 de julho de 1902"); 
        }
        else if (jRVasco.isSelected()){
        JOptionPane.showMessageDialog(null, "21 de agosto de 1898");
        }
        else if (jRFlamengo.isSelected()){
        JOptionPane.showMessageDialog(null, "17 de novembro de 1895");
        }
        else if (jRCoritiba.isSelected()){
        JOptionPane.showMessageDialog(null, "12 de outubro de 1909");
        }
        else if (jRAtleticoMG.isSelected()){
        JOptionPane.showMessageDialog(null, "25 de março de 1908");
        }
        else if (jRAtleticoPR.isSelected()){
        JOptionPane.showMessageDialog(null, "26 de março de 1924");
        }
        else if (jRCruzeiro.isSelected()){
        JOptionPane.showMessageDialog(null, "02 de janeiro de 1921");
        }
        else if (jRInternacional.isSelected()){
        JOptionPane.showMessageDialog(null, "04 de abril de 1909");
        }
        else if (jRGremio.isSelected()){
        JOptionPane.showMessageDialog(null, "15 de setembro de 1903");
        }
        else if (jRSport.isSelected()){
        JOptionPane.showMessageDialog(null, "13 de maio de 1905");
        }
        {
   
    }//GEN-LAST:event_jButton1ActionPerformed
}
    private void jRCorinthiansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCorinthiansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRCorinthiansActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fundacao_Times.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fundacao_Times.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fundacao_Times.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fundacao_Times.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fundacao_Times().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jBGGrupoOpcoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRAtleticoMG;
    private javax.swing.JRadioButton jRAtleticoPR;
    private javax.swing.JRadioButton jRBotaFogo;
    private javax.swing.JRadioButton jRCorinthians;
    private javax.swing.JRadioButton jRCoritiba;
    private javax.swing.JRadioButton jRCruzeiro;
    private javax.swing.JRadioButton jRFlamengo;
    private javax.swing.JRadioButton jRFluminense;
    private javax.swing.JRadioButton jRGremio;
    private javax.swing.JRadioButton jRInternacional;
    private javax.swing.JRadioButton jRPalmeiras;
    private javax.swing.JRadioButton jRSantos;
    private javax.swing.JRadioButton jRSaoPaulo;
    private javax.swing.JRadioButton jRSport;
    private javax.swing.JRadioButton jRVasco;
    // End of variables declaration//GEN-END:variables
}
